paths:
  data:
    data_dir: "data"
    raw_dir: "data/raw"
    processed_dir: "data/processed"
    events_dir: "data/event"
  reports:
    reports_dir: "reports"
    plots_dir: "reports/plots"
  model:
    model_dir: "models/"
